/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intmayuscula;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLPrimerNro = new javax.swing.JLabel();
        jlSegundoNro = new javax.swing.JLabel();
        jtprimerNum = new javax.swing.JTextField();
        jtSegundonum = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jbLimpiar = new javax.swing.JButton();
        jlResultado = new javax.swing.JLabel();
        jbSumar = new javax.swing.JButton();
        jbRestar = new javax.swing.JButton();
        jbMultiplicar = new javax.swing.JButton();
        jDividir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("CALCULADORA");

        jLPrimerNro.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jLPrimerNro.setForeground(new java.awt.Color(0, 51, 102));
        jLPrimerNro.setText("PRIMER NRO");

        jlSegundoNro.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlSegundoNro.setForeground(new java.awt.Color(0, 0, 102));
        jlSegundoNro.setText("SEGUNDO NRO");

        jbLimpiar.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jbLimpiar.setForeground(new java.awt.Color(0, 0, 102));
        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jlResultado.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        jlResultado.setForeground(new java.awt.Color(0, 51, 102));
        jlResultado.setText("RESULTADO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jbLimpiar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jlResultado)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlResultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jbLimpiar)
                .addGap(19, 19, 19))
        );

        jbSumar.setFont(new java.awt.Font("Book Antiqua", 2, 14)); // NOI18N
        jbSumar.setForeground(new java.awt.Color(0, 0, 51));
        jbSumar.setText("Sumar");
        jbSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSumarActionPerformed(evt);
            }
        });

        jbRestar.setFont(new java.awt.Font("Book Antiqua", 2, 14)); // NOI18N
        jbRestar.setForeground(new java.awt.Color(0, 0, 51));
        jbRestar.setText("Restar");
        jbRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRestarActionPerformed(evt);
            }
        });

        jbMultiplicar.setFont(new java.awt.Font("Book Antiqua", 2, 14)); // NOI18N
        jbMultiplicar.setForeground(new java.awt.Color(0, 0, 51));
        jbMultiplicar.setText("Multiplicar");
        jbMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMultiplicarActionPerformed(evt);
            }
        });

        jDividir.setFont(new java.awt.Font("Book Antiqua", 2, 14)); // NOI18N
        jDividir.setForeground(new java.awt.Color(0, 0, 51));
        jDividir.setText("Dividir");
        jDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDividirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLPrimerNro))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlSegundoNro)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbSumar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbRestar)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtSegundonum, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtprimerNum, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jbMultiplicar)
                                .addGap(18, 18, 18)
                                .addComponent(jDividir)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPrimerNro, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtprimerNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSegundoNro)
                    .addComponent(jtSegundonum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSumar)
                    .addComponent(jbRestar)
                    .addComponent(jbMultiplicar)
                    .addComponent(jDividir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        jtprimerNum.setText("");
        jtSegundonum.setText("");
       jlResultado.setText("Resultado");
               
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSumarActionPerformed
    try{
            int nro1=Integer.parseInt(jtprimerNum.getText());
            int nro2=Integer.parseInt(jtSegundonum.getText());
            int resultado=nro1+nro2;
            jlResultado.setText(resultado+"");
       }catch(NumberFormatException nf){
           JOptionPane.showMessageDialog(this,"usted debe ingresar un Nro");
           jtprimerNum.setText("");
           jtSegundonum.setText("");
    }       
    }//GEN-LAST:event_jbSumarActionPerformed

    private void jbRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRestarActionPerformed
try{
            int nro1=Integer.parseInt(jtprimerNum.getText());
            int nro2=Integer.parseInt(jtSegundonum.getText());
            int resultado=nro1-nro2;
            jlResultado.setText(resultado+"");
       }catch(NumberFormatException nf){
           JOptionPane.showMessageDialog(this,"usted debe ingresar un Nro");
           jtprimerNum.setText("");
           jtSegundonum.setText("");
    }               // TODO add your handling code here:
    }//GEN-LAST:event_jbRestarActionPerformed

    private void jbMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMultiplicarActionPerformed
try{
            int nro1=Integer.parseInt(jtprimerNum.getText());
            int nro2=Integer.parseInt(jtSegundonum.getText());
            int resultado=nro1*nro2;
            jlResultado.setText(resultado+"");
       }catch(NumberFormatException nf){
           JOptionPane.showMessageDialog(this,"usted debe ingresar un Nro");
           jtprimerNum.setText("");
           jtSegundonum.setText("");
    }               // TODO add your handling code here:
    }//GEN-LAST:event_jbMultiplicarActionPerformed

    private void jDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDividirActionPerformed
try{
            int nro1=Integer.parseInt(jtprimerNum.getText());
            int nro2=Integer.parseInt(jtSegundonum.getText());
            int resultado=nro1/nro2;
            jlResultado.setText(resultado+"");
       }catch(NumberFormatException nf){
           JOptionPane.showMessageDialog(this,"usted debe ingresar un Nro");
           jtprimerNum.setText("");
           jtSegundonum.setText("");
    }               // TODO add your handling code here:
    }//GEN-LAST:event_jDividirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jDividir;
    private javax.swing.JLabel jLPrimerNro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbMultiplicar;
    private javax.swing.JButton jbRestar;
    private javax.swing.JButton jbSumar;
    private javax.swing.JLabel jlResultado;
    private javax.swing.JLabel jlSegundoNro;
    private javax.swing.JTextField jtSegundonum;
    private javax.swing.JTextField jtprimerNum;
    // End of variables declaration//GEN-END:variables
}
